language: ruby
rvm:
  - 2.1
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec spec
bundler_args: --without development
addons:
  code_climate:
    repo_token: b4807a860e0c191bd0c36f8a7edab2cf50ac32a0aab105a125adf4f3216cfc4a